url: ''
baseurl: ''
title: 'CU Narrative Intelligence Lab'

plugins:
  - jekyll-postcss-v2

gems:
  - jekyll-inline-svg

svg:
  optimize: true

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - documents/

# Required if you want to move pages into a separate directory
include: ['_pages']
relative_permalinks: false

collections_dir: collections  # Store all collections inside "collections" folder

collections:
  projects:
    output: true   # Generate individual pages for each project
    permalink: /projects/:path/  # Force correct URL structure
    name: "projects"  # Ensure Jekyll recognizes _projects as projects
    image_folder: "projects"  # Default image folder for projects
  category:
    output: true
  events:
    output: true
    permalink: /events/:path/
    name: "events"
    image_folder: "events"  # Default image folder for projects

defaults:
  - scope:
      path: "collections/_projects"  # Applies to all files in the projects collection
      type: "projects"
    values:
      layout: project
      image_folder: "projects"

  - scope:
      path: "collections/_events"  # Applies to all files in the projects collection
      type: "events"
    values:
      layout: project
      image_folder: "events"
