url: ''
baseurl: ''
title: 'CU Narrative Intelligence Lab'

plugins:
  - jekyll-postcss-v2

gems:
  - jekyll-inline-svg

svg:
  optimize: true

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - documents/

collections_dir: collections  # Store all collections inside "collections" folder

collections:
  team:
  projects:
    output: true   # Generate individual pages for each project
    permalink: /projects/:path/  # Force correct URL structure
    name: "projects"  # Ensure Jekyll recognizes _projects as projects
  category:
    output: true

defaults:
  - scope:
      path: "collections/_projects"  # Applies to all files in the projects collection
      type: "projects"
    values:
      layout: project
