url: ''
baseurl: ''
title: 'CU Narrative Intelligence Lab'

plugins:
  - jekyll-postcss-v2

gems:
  - jekyll-inline-svg

svg:
  optimize: true

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - documents/

collections_dir: collections  # Store all collections inside a single "collections" folder

collections:
  team:
  projects:
    output: true  # Allow individual pages
    permalink: /projects/:path/
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
